// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-6BpPveZyoa7Us0qPB82gfzF72YSvZBc',
    appId: '1:442075112979:web:a2aba2685bd2fddac401e6',
    messagingSenderId: '442075112979',
    projectId: 'teste-tecnico-flutter',
    authDomain: 'teste-tecnico-flutter.firebaseapp.com',
    storageBucket: 'teste-tecnico-flutter.firebasestorage.app',
    measurementId: 'G-1CZ9NNEQYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBClgFOOK7mFplzx3yXrX6-rLS7i_2qzME',
    appId: '1:442075112979:android:8ddebf7bbd8f98aac401e6',
    messagingSenderId: '442075112979',
    projectId: 'teste-tecnico-flutter',
    storageBucket: 'teste-tecnico-flutter.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI6lPzpOcPs_oONQPpbkBwiMzugvpDBOM',
    appId: '1:442075112979:ios:ee1e59f36b7d522ac401e6',
    messagingSenderId: '442075112979',
    projectId: 'teste-tecnico-flutter',
    storageBucket: 'teste-tecnico-flutter.firebasestorage.app',
    iosBundleId: 'com.example.testeTecnico',
  );
}
